### PR TITLE
Add autorefreshing and .ionide configuration

### PR DESCRIPTION
**Pull request by tpetricek**
@Krzysztof-Cieslak - this looks pretty much done to me :) was there anything else you wanted to add?

### CODE REVIEW

**Comment by tpetricek** [comment]
What does the `port=8083` in the `.ionide` config do? What happens when you run two journals? (If we omitted the parameter, would Ionide pick a new random port?)

(Although maybe having a port in the config is better - people can easily change it)

**Comment by tpetricek** [comment]
Also, why did you change the `ReadKey` to `Sleep(-1)`?

(I think using sleep is OK, but it might be less easy to use the runner from the command line...)

**Comment by Krzysztof-Cieslak** [comment]
We would also need to update default FsLab template which is here https://github.com/fslaborg/FsLab/blob/master/src/misc/styles/template.html and add there following JS snippet:
```JS
<script language="javascript" type="text/javascript">
        function init()
        {
            websocket = new WebSocket("ws://localhost:8083/websocket");
            websocket.onmessage = function(evt) { location.reload(); };
        }
        window.addEventListener("load", init, false);
    </script>
```

At the moment Ionide web preview is supporting only one preview at time. `Port` is information both for Ionide and FAKE script (it's passed there as environmental variable) - basically I make command `(linuxPrefix) command script build port=port (parameters)` (so in this case : `packages\FAKE\tools\FAKE.exe build.fsx run port=8083 --fsiargs -d:NO_FSI_ADDPRINTER`) and execute it. After I detect occurrence of `startString` in standard output, I set iframe source to `host:port\startingFile`. I would leave port as it is in config - it just gives more configuration possibilities to user without any drawback (at least from Ionide point of view, FAKE script can ignore environmental variable it's getting - in such case user must be sure config is set to the port on each content is hosted. )

When script is run not from console but executed from other program (in our case by Atom / node) `ReadKey` throws exception.

**Comment by Krzysztof-Cieslak** [comment]
Also, since it's using getValueOrDefault to get environmental variable (with default set up to previously hard-coded value) it will have no impact for users not using `Ionide`. But they will get auto-refresh for free anyway ;)

**Comment by Krzysztof-Cieslak** [comment]
If `port` entry in config file is omitted it's set up to default value (8083). 

The one problem right now is that port is hard-coded also in template file. Actually it might be better (in this case) to spawn suave server always on good port (i.e. this hard-coded in template file) and not on port send by Ionide to build script (in such case `port` entry in config would be just used for opening good page on Ionide side of things)

**Comment by tpetricek** [comment]
Is there some way to change it back to `Console.ReadLine()` rather than `Thread.Sleep(-1)` for the waiting?

The trouble is that when you start the process from console and use `Thread.Sleep(-1)`, then it is really hard to kill it :-). Perhaps Ionide could invoke some other target that uses `Sleep`, but the default `run` target could use `Console.Readline`?

**Comment by Krzysztof-Cieslak** [comment]
Yeah, sure. We can do something like that. I'll make PR

**Pull request merged**
